apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-handler-pv
  labels:
    stage: database-handler
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /custom/data/database-handler
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-handler-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi