apiVersion: v1
kind: Service
metadata:
  name: beverage-service
spec:
  ports:
  - port: 2400
    targetPort: 9998
    protocol: TCP
  type: NodePort
  selector:
    app: beerz
---
apiVersion: v1
kind: Service
metadata:
  name: management-service
spec:
  ports:
    - port: 2500
      targetPort: 9997
      protocol: TCP
  type: NodePort
  selector:
    app: beerz